# Generated by Django 6.0 on 2026-01-02 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('khach_san', '0002_alter_loaiphong_id_alter_phong_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dich_vu', models.CharField(max_length=100)),
                ('gia', models.PositiveIntegerField()),
                ('don_vi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DatPhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_khach', models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='Mã khách')),
                ('ten_khach', models.CharField(max_length=100, verbose_name='Tên khách')),
                ('loai_khach', models.CharField(choices=[('vang_lai', 'Vãng lai'), ('tour', 'Khách tour đoàn'), ('booking', 'Booking'), ('agoda', 'Agoda'), ('traveloka', 'Traveloka')], max_length=20, verbose_name='Loại khách')),
                ('ngay_nhan', models.DateField(verbose_name='Ngày nhận phòng')),
                ('ngay_tra_du_kien', models.DateField(verbose_name='Ngày trả dự kiến')),
                ('ngay_tra', models.DateField(blank=True, null=True, verbose_name='Ngày trả phòng')),
                ('dang_o', models.BooleanField(default=True, verbose_name='Đang ở')),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='khach_san.phong', verbose_name='Phòng')),
            ],
            options={
                'ordering': ['-dang_o', '-ngay_nhan'],
            },
        ),
        migrations.CreateModel(
            name='SuDungDichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=1)),
                ('thoi_diem', models.DateTimeField(auto_now_add=True)),
                ('dat_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dat_phong.datphong')),
                ('dich_vu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dat_phong.dichvu')),
            ],
        ),
    ]
