# Generated by Django 6.0 on 2026-01-03 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat_phong', '0001_initial'),
        ('khach_san', '0002_alter_loaiphong_id_alter_phong_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LichHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khach', models.CharField(max_length=200)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=30)),
                ('ngay_den', models.DateField()),
                ('gio_den', models.TimeField(blank=True, null=True)),
                ('ghi_chu', models.TextField(blank=True)),
                ('trang_thai', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_hen', to='khach_san.phong')),
            ],
            options={
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
