# Generated by Django 5.2.9 on 2026-01-02 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiPhong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=100)),
                ('gia_mot_dem', models.PositiveIntegerField(verbose_name='Giá / đêm (VND)')),
            ],
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phong', models.CharField(max_length=10, unique=True)),
                ('trang_thai', models.CharField(choices=[('trong', 'Trống'), ('dang_thue', 'Đang thuê'), ('dang_bao_tri', 'Đang bảo trì')], default='trong', max_length=20)),
                ('loai_phong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='khach_san.loaiphong')),
            ],
        ),
    ]
